# Make sure to fill in your spotify client_secret information
spotify_token = "BQAThtzTluHyegr7tyZ9qRZk5CGSJs27Dg9bEA8o4VodbzOswrYlPnGa6UqJhszKBhT0bS0Pe6MH1xuJF86R_n-Rm3T554AlIy9P1vi9rwQuJWgXWbqxnazQzNEN66xjsW1CBV7jfnpuBTPSKBPLnD1JOJWCVFdlULINUudWw56PFDTLZ5wRrYMS7Hi4eCODIyMvmS8g-DBcMjVhWYUA1cVgQ1qYSmMGpz7YAdWtZBWPHeYbUv_mTqt1hyDUqxYgJ1uXBTXzKVJPXvN_l3doXQ"
spotify_user_id = "schraeder.br"